# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SOAP-DateTime
version:      0.02
version_from: lib/SOAP/DateTime.pm
installdirs:  site
requires:
    Date::Manip:                   0
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.28
